# Generated by Django 3.2.8 on 2021-10-26 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolistapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='bookmark',
            field=models.BooleanField(default=False),
        ),
    ]
