# Generated by Django 3.2.8 on 2021-10-28 14:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('todolistapp', '0002_task_bookmark'),
    ]

    operations = [
        migrations.CreateModel(
            name='Collections',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collection', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='todolistapp.collections')),
                ('title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='todolistapp.task')),
            ],
        ),
        migrations.AddField(
            model_name='collections',
            name='task',
            field=models.ManyToManyField(through='todolistapp.Enrollment', to='todolistapp.Task'),
        ),
    ]
