# Generated by Django 3.2.8 on 2021-10-29 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todolistapp', '0003_auto_20211028_2018'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='enrollment',
            unique_together={('title', 'collection')},
        ),
    ]
